#!/bin/bash --posix

##
##  Goal:   Ease the creation, installation etc. of LibreOffice addons and calc addins
##
##  Use:    liboaddon install <oxt>
##          liboaddon list [full]
##          liboaddon remove [identifier]
##          liboaddon package <module> <source.py>
##
##  where   install installs the addon packaged in the given oxt file pathname
##          list    list identifiers of installed addons
##          full    list more information about installed addons
##          remove  remove an installed addon by identifier
##
##          package create an oxt file starting from python source
##            <module> is the name of the Python class to be packaged
##            <source.py> is that path of the Python class's implementation
##            the result is <module>.oxt and a subdirectory named <module>
##            the subdirectory may safely be deleted
##
#   Caveat: The package verb of this bash script relies on a python script
#           named capp.py, which must have been deployed correctly.
#
#   Copyright (C) 2012, 2016, NewForester
#   Released under the terms of the GNU GPL v2
#
#   Inspired by the DoobieDoo example for Windows
#   Created by jan@biochemfusion.com, April 2009

# print out header comment

usage() { (sed -e "/^###/d" -e "/^##/!d" $0 && echo -e "\e[35m${0##*/}: \e[31m$@\e[0m") >&2; }

# process options

liboroot="/usr/lib/libreoffice";

unopkg="${liboroot}/program/unopkg";

while [[ -n "${1%%[!-]*}" ]]; do
    case $1 in
      (--help)
        usage "I hope that was helpful";
        exit 1;
        ;;
      (*)
        usage "bad option \"$1\"";
        exit 1;
        ;;
    esac
done

xmlManifest ()
{
    fmtmanifest='<manifest:file-entry manifest:media-type=\"application/vnd.sun.star.%s\" manifest:full-path=\"%s\"/>'

    echo '<manifest:manifest>'
    printf "    $fmtmanifest\n" 'uno-typelibrary;type=RDB' "$1"
    printf "    $fmtmanifest\n" 'uno-component;type=Python' "$2"
    printf "    $fmtmanifest\n" 'configuration-data' "$3"
    echo '</manifest:manifest>'
}

# do it

case "$*" in
  ("package "*)
    pName=$2;
    pFile=$3;
    xName="X${pName}";

    if [[ ! -r "${pFile}" ]]; then
        usage "cannot read Python source file \"${pFile}\"";
        exit 1;
    fi

    idlc="${liboroot}/sdk/bin/idlc";
    python="${liboroot}/program/python";

    if [[ ! -x "${idlc}" ]]; then
        usage "suspect the SDK has not been installed";
        exit 1;
    fi

    if [[ -d "${liboroot}/ure/bin" ]]; then
        # Old LibreOffice 3.x
        regmerge="${liboroot}/ure/bin/regmerge";
        cabin="${PWD}/python2";
    else
        # New LibreOffice 5.x
        regmerge="${liboroot}/program/regmerge";
        cabin="${PWD}/python3";
    fi

    rm -fr ${pName} ${pName}.oxt;
    mkdir -p ${pName}/META-INF;
    cp -pf ${pFile} ${pName};
    pFile=${pFile##*/};

    cd ${pName} > /dev/null;
    ${python} ${cabin}/idlGenerate ${pName} ${pFile} > ${xName}.idl;
    ${idlc} -w -I ${liboroot}/sdk/idl ${xName}.idl;
    ${regmerge} ${xName}.rdb /UCR ${xName}.urd;

    ${python} ${cabin}/xcuGenerate ${pName} ${pFile} > ${pName}.xcu;
    ${python} ${cabin}/xmlGenerate ${pName} ${pFile} > description.xml;
    xmlManifest ${xName}.rdb ${pFile} ${pName}.xcu > META-INF/manifest.xml;

#    7z a -r -x'!'${xName}.urd -x'!'${xName}.idl -tzip ../${pName}.oxt *;
    zip -r ../${pName}.oxt * -x ${xName}.urd ${xName}.idl;
    cd -;
    ;;
  ("install "*)
    ${unopkg} add -f $2;
    ;;
  ("list")
    ${unopkg} list | sed -e '/^Identifier: /!d' -e 's/^Identifier: //';
    ;;
  ("list full")
    echo $*
    ${unopkg} list
    ;;
  ("remove "*)
    ${unopkg} remove $2;
    ;;
  (*)
    usage "do not know how to \"$*\"" - am I missing something ?;
    exit 1;
    ;;
esac

exit;

# EOF
